version: '3.8'
services:
  api:
    container_name: "high_kurlyty_${NODE_ENV}"
    image: "high_kurlyty_${NODE_ENV}"
    environment:
      - NODE_ENV:${NODE_ENV}
    build:
      context: ./app
      target: "${NODE_ENV}"
      dockerfile: Dockerfile
    entrypoint: ["yarn", "start:${NODE_ENV}"]
    env_file:
      - .${NODE_ENV}.env
    ports:
      - 3000:3000
    networks:
      - nesjs-network
    volumes:
      - ./app:/usr/src/app
      - /usr/src/app/node_modules
    restart: unless-stopped
networks:
  nesjs-network:
